version: '3.9'

services:
  app:
    restart: always
    build: ./app
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      # - app-django:/usr/src/app
      - .:/code
      - app-static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn sams.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - app-static:/www/static
      # - "./app:/var/www/html"
    links:
      - app:app

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: .env

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  # app-django:
  app-static:
  pgdata:
  redisdata: