services:
  app:
    restart: unless-stopped
    build:
      context: ./app
      target: dev
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: 'true'
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./app:/app
    # entrypoint: /app/docker-entrypoint-dev.sh


  postgres:
    restart: unless-stopped
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/


  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data:
