services:
  app:
    restart: unless-stopped
    build:
      context: ./app
      target: prod
    env_file: .env
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - app-static:/app/static

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - app-static:/app/static
    links:
      - app:app

  postgres:
    restart: unless-stopped
    image: postgres:latest
    env_file: .env
    ports:
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - "6379"
    volumes:
      - redis-data:/data

volumes:
  app-static:
  pg-data:
  redis-data:
