# Generated by Django 5.0.6 on 2024-05-28 12:30

from django.db import migrations


def populate_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Teachers")
    Group.objects.get_or_create(name="Students")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(populate_groups),
    ]
