# Generated by Django 5.0.6 on 2024-05-28 12:35

from django.db import migrations
from django.contrib.auth.hashers import make_password


def populate_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")

    teachers_group = Group.objects.get(name="Teachers")
    students_group = Group.objects.get(name="Students")

    # Create an admin account
    user0 = User(
        pk=1,
        username='admin',
        first_name='SAMS',
        last_name='Admin',
        password='pbkdf2_sha256$720000$TZiaix8ZLMafySfdr56xZw$vjQwjM9IU+1SOF+2eqc7tTfPdtWATZLfwjuX98vGR5I=',
        is_staff=True,
        is_superuser=True,
    )
    user0.save()

    # Create users for the Teachers group
    user1 = User(
        pk=101,
        username='john_doe',
        email='john_doe@example.com',
        first_name='John',
        last_name='Doe',
        password='pbkdf2_sha256$720000$MJ5W4CyNptLgM8avtNnVXm$OHZYFWbNkVi8zj9lDIFnx2LBu0smstebRYnmM+cOfug=',
        is_staff=False,
        is_superuser=False
    )
    user1.save()
    user1.groups.add(teachers_group)
    user1.save()

    user2 = User(
        pk=102,
        username='jane_doe',
        email='jane_doe@example.com',
        first_name='Jane',
        last_name='Doe',
        password='pbkdf2_sha256$720000$Zy9oBjOOW3PQpCSHActBIA$85gEQXXw3vbiJ7nAWpWPwgfHv54mnQ+3MMmBpwrZsh8=',
        is_staff=False,
        is_superuser=False
    )
    user2.save()
    user2.groups.add(teachers_group)
    user2.save()

    # Create users for the Students group
    user3 = User(
        pk=1001,
        username='alice_smith',
        email='alice_smith@example.com',
        first_name='Alice',
        last_name='Smith',
        password='pbkdf2_sha256$720000$1UCxt4mjACScdKQpXdcVNI$CBFlAGB+P+ybg2XbK3vNzboZ/vLBGvCc9um+ywTH5r4=',
        is_staff=False,
        is_superuser=False,
    )
    user3.save()
    user3.groups.add(students_group)
    user3.save()

    user4 = User(
        pk=1002,
        username='bob_smith',
        email='bob_smith@example.com',
        first_name='Bob',
        last_name='Smith',
        password='pbkdf2_sha256$720000$zWlncB4EXSzakr5iVWTPOz$fNnceGOtjnD1yZjOrLAN/K2UASvHUNYteGdidYB7FhQ=',
        is_staff=False,
        is_superuser=False,
    )
    user4.save()
    user4.groups.add(students_group)
    user4.save()

    user5 = User(
        pk=1003,
        username='charlie_smith',
        email='charlie_smith@example.com',
        first_name='Charlie',
        last_name='Smith',
        password='pbkdf2_sha256$720000$ONjH5lzeEvdHKYupyUJXsI$GFyAJ4zCWIqNU+OYt+tGEFDMr8S2Q+e0eGNYbzErHOE=',
        is_staff=False,
        is_superuser=False,
    )
    user5.save()
    user5.groups.add(students_group)
    user5.save()


def undo_populate_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.filter(pk__in=[1, 101, 102, 1001, 1002, 1003]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_populate_groups'),
    ]

    operations = [
        migrations.RunPython(populate_users, undo_populate_users),
    ]