# Generated by Django 5.0.6 on 2024-05-29 16:03

from django.db import migrations


def populate_courses(apps, schema_editor):
    Course = apps.get_model("core", "Course")
    CourseRegistration = apps.get_model("core", "CourseRegistration")
    User = apps.get_model("auth", "User")

    john_doe = User.objects.get(username="john_doe")
    jane_doe = User.objects.get(username="jane_doe")
    alice_smith = User.objects.get(username="alice_smith")
    bob_smith = User.objects.get(username="bob_smith")
    charlie_smith = User.objects.get(username="charlie_smith")

    course1 = Course.objects.create(
        owner=john_doe,
        title="Introduction to Django",
        description="A beginner-friendly course on Django",
        start_date="2024-06-01",
        end_date="2024-06-30",
        max_seats=5,
        is_public=True,
        is_active=True,
    )

    course2 = Course.objects.create(
        owner=john_doe,
        title="Intermediate Django",
        description="A course for those who have completed the Introduction to Django course",
        start_date="2024-07-01",
        end_date="2024-07-31",
        max_seats=3,
        is_public=True,
        is_active=True,
    )

    course3 = Course.objects.create(
        owner=jane_doe,
        title="Advanced Django",
        description="An advanced course on Django",
        start_date="2024-08-01",
        end_date="2024-08-31",
        max_seats=2,
        is_public=True,
        is_active=True,
    )

    # Register users for the courses
    CourseRegistration.objects.create(user=alice_smith, course=course1)
    CourseRegistration.objects.create(user=alice_smith, course=course2)

    CourseRegistration.objects.create(user=bob_smith, course=course2)

    CourseRegistration.objects.create(user=charlie_smith, course=course3)


def undo_populate_courses(apps, schema_editor):
    Course = apps.get_model("core", "Course")
    CourseRegistration = apps.get_model("core", "CourseRegistration")
    User = apps.get_model("auth", "User")

    john_doe = User.objects.get(username="john_doe")
    jane_doe = User.objects.get(username="jane_doe")
    alice_smith = User.objects.get(username="alice_smith")
    bob_smith = User.objects.get(username="bob_smith")
    charlie_smith = User.objects.get(username="charlie_smith")

    Course.objects.filter(owner=john_doe).delete()
    Course.objects.filter(owner=jane_doe).delete()

    CourseRegistration.objects.filter(user=alice_smith).delete()
    CourseRegistration.objects.filter(user=bob_smith).delete()
    CourseRegistration.objects.filter(user=charlie_smith).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_course_model'),
    ]

    operations = [
        migrations.RunPython(populate_courses, undo_populate_courses),
    ]
